### PR TITLE
Added svgs in editor

### PR DESCRIPTION
**Pull request by srijit2002**
Added svgs in editor and updated `mjxgui.js` and `mjxgui.min.js`
Fixes issue #2

### CODE REVIEW

**Review by hrushikeshrv — COMMENTED** [review]
Everything looks good, have you tested creating a few equations using the mjxgui.js and mjxgui.min.js files?

**Comment by srijit2002** [comment]
@hrushikeshrv  Yup I have tested

**Comment by hrushikeshrv** [comment]
Great! I'll test it asap and merge the pr by tomorrow :)

**Comment by srijit2002** [comment]
@hrushikeshrv thanks a lot. :-)

**Comment by hrushikeshrv** [comment]
Thanks for contributing. Good luck for hacktoberfest!

**Pull request merged**
