### PR TITLE
Balogun14/issue18

### PR DESCRIPTION
**Pull request by balogun14**
I made the enhancement and fixed the formatting

### CODE REVIEW

**Review by jatin-47 — CHANGES_REQUESTED** [review]
You have formatted the whole `ui.js`. Just make the desired changes at the places you want.

**Comment by balogun14** [comment]
@jatin-47 i can see that my formatter did that by itself so ill fix it now

**Review by balogun14 — COMMENTED** [review]
the formatting was caused by prettier i did not know that is what you meant befor

**Review by balogun14 — COMMENTED** [review]
forgot to fetch the changes made before pushing

**Pull request closed without merging**
