### PR TITLE
Resolve #27: Fix Text Overflow in Input Editor for Large Equations

### LINKED ISSUE #27: Text Overflow in Input Editor for Large Equations
# Description:

## Bug Report

I’ve encountered a bug in the MJXGUI editor where the text starts to overflow when a large amount of elements are inputted.

## Details

When writing a large equation in the input editor, the text starts to overflow after reaching a max width of around 520px. This results in some parts of the equation being cut off from view, which hampers the user experience.

### Steps to Reproduce

- Open the MJXGUI editor.

- Start inputting a large equation until the width of the equation exceeds around 520px.

- Observe that the text starts to overflow.

## Expected Behavior

The input editor should properly handle large equations and prevent text overflow. This could potentially be achieved by introducing a scroll feature or expanding the width of the input editor as needed.

## Screenshots

image

### PR DESCRIPTION
**Pull request by azr-arch**
This PR resolves issue #27 where the input editor was experiencing text overflow when handling large equations.

### CODE REVIEW

**Comment by hrushikeshrv** [comment]
It looks like you've also committed your `.vscode` folder, which should not be included.

**Review by hrushikeshrv — CHANGES_REQUESTED** [review]
The changes you have made in `docs/css/mjxgui.css` look good 👍🏻 
You should also make these same changes in `src/mjxgui.css` and commit that file as well.

**Comment by azr-arch** [comment]
> The changes you have made in `docs/css/mjxgui.css` look good 👍🏻 You should also make these same changes in `src/mjxgui.css` and commit that file as well.

is it okay now ?

**Review by hrushikeshrv — APPROVED** [review]

**Comment by hrushikeshrv** [comment]
Thanks @azr-arch 👍🏻

**Pull request merged**
