### PR TITLE
Add Tooltip Feature to Editor Keys

### PR DESCRIPTION
**Pull request by azr-arch**
**Description**:

This PR addresses the feature request outlined in issue #26.

**Feature Description**:
The goal of this feature is to enhance the user experience by providing tooltips for the keys in the MJXGUI editor. When a user hovers over a key, a tooltip will appear displaying a brief description or name of the key. This is particularly useful for keys that represent complex mathematical symbols or functions, helping users understand their meaning without needing to refer to external resources.

**Implementation Details**:
The feature is implemented by adding a title attribute to each key during their creation in the JavaScript code. The title attribute holds the description or name of the key, which is displayed as a tooltip when the user hovers over the key.

For example:
```html
<span class="mjxgui-btn mjxgui-greek-letter" data-latex-data="Alpha" title="Alpha">&Alpha;</span>
```
In this example, when you hover over the Alpha button, a tooltip will appear showing “Alpha”.

This PR includes all necessary changes to implement this feature and has been tested for functionality.

### CODE REVIEW

**Comment by hrushikeshrv** [comment]
Hi @azr-arch, the functionality looks good, but it seems you've run an autoformatter over `ui.js` again.

**Comment by azr-arch** [comment]
@hrushikeshrv  whats the format, i'll repush it, also have to add vscode folder in gitignore what do you say ?

**Comment by azr-arch** [comment]
@hrushikeshrv  check the new one, is it correct ?, i tried making the `editorDiv.innerHTML` code in one line, but unable to do it.

**Comment by hrushikeshrv** [comment]
Hi @azr-arch, sorry for the delay. Looks good 👍🏻

**Pull request merged**
